# Generated by Django 5.2.5 on 2025-11-03 04:45

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KenyaCounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=254)),
                ('pop_2009', models.BigIntegerField()),
                ('country', models.CharField(max_length=5)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='KenyaSubCounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=254)),
                ('province', models.CharField(max_length=254)),
                ('county', models.CharField(max_length=254)),
                ('subcounty', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Kenyawards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=40)),
                ('subcounty', models.CharField(max_length=80)),
                ('ward', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(blank=True, help_text="Unique identifier for the project (from 'Project ID')", max_length=50, null=True, unique=True)),
                ('name', models.CharField(help_text="Project name (from 'Project Name')", max_length=200)),
                ('sector', models.CharField(blank=True, help_text="Sector of the project (from 'Sector')", max_length=100)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('delayed', 'Delayed')], default='planned', help_text="Current project status (from 'Status')", max_length=20)),
                ('project_manager', models.CharField(blank=True, help_text="Name of the project manager (from 'Project Manager')", max_length=200)),
                ('person_responsible', models.CharField(blank=True, help_text="Name of person responsible (from 'Person Responsible')", max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Explicit latitude value', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Explicit longitude value', max_digits=9, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='GIS Point from Latitude/Longitude', null=True, srid=4326)),
                ('county', models.CharField(help_text='County where the project is located', max_length=100)),
                ('start_date', models.DateField(help_text="Start date of the project (from 'Start Date')")),
                ('end_date', models.DateField(help_text="End date of the project (from 'End Date')")),
                ('budget', models.DecimalField(decimal_places=2, help_text="Project budget in KES (from 'Budget (KES)')", max_digits=18)),
                ('description', models.TextField(blank=True, null=True)),
                ('implementing_agency', models.CharField(blank=True, max_length=200)),
                ('contractor', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CitizenReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('progress', 'Progress Report'), ('issue', 'Issue Report'), ('complaint', 'Complaint'), ('suggestion', 'Suggestion')], max_length=50)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='citizen_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citizen_reports', to='app.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='chat_images/')),
                ('file', models.FileField(blank=True, null=True, upload_to='chat_files/')),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File'), ('system', 'System Message')], default='text', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='app.project')),
                ('read_by', models.ManyToManyField(blank=True, related_name='read_messages', to=settings.AUTH_USER_MODEL)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='app.projectchatmessage')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProjectUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('progress_percentage', models.IntegerField(default=0)),
                ('photo', models.ImageField(blank=True, upload_to='project_updates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='app.project')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
