# Generated by Django 5.2.5 on 2025-09-19 17:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_county_kenyaward_subcounty'),
    ]

    operations = [
        migrations.CreateModel(
            name='KenyaCounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=254)),
                ('pop_2009', models.BigIntegerField()),
                ('country', models.CharField(max_length=5)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='KenyaSubCounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=254)),
                ('province', models.CharField(max_length=254)),
                ('county', models.CharField(max_length=254)),
                ('subcounty', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Kenyawards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=40)),
                ('subcounty', models.CharField(max_length=80)),
                ('ward', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.DeleteModel(
            name='County',
        ),
        migrations.DeleteModel(
            name='KenyaWard',
        ),
        migrations.DeleteModel(
            name='SubCounty',
        ),
    ]
