# Generated by Django 5.2.5 on 2025-09-20 03:14

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_kenyacounty_kenyasubcounty_kenyawards_delete_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kenyacounty',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
        migrations.AlterField(
            model_name='kenyasubcounty',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
        migrations.AlterField(
            model_name='kenyawards',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
