# Generated by Django 5.2.5 on 2025-09-21 13:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_kenyacounty_geom_alter_kenyasubcounty_geom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.DecimalField(decimal_places=2, help_text="Project budget in KES (from 'Budget (KES)')", max_digits=18),
        ),
        migrations.AlterField(
            model_name='project',
            name='county',
            field=models.CharField(help_text='County where the project is located', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(help_text="End date of the project (from 'End Date')"),
        ),
        migrations.AlterField(
            model_name='project',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Explicit latitude value', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='GIS Point from Latitude/Longitude', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='project',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Explicit longitude value', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text="Project name (from 'Project Name')", max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='person_responsible',
            field=models.CharField(blank=True, help_text="Name of person responsible (from 'Person Responsible')", max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(blank=True, help_text="Unique identifier for the project (from 'Project ID')", max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_manager',
            field=models.CharField(blank=True, help_text="Name of the project manager (from 'Project Manager')", max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='sector',
            field=models.CharField(blank=True, help_text="Sector of the project (from 'Sector')", max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(help_text="Start date of the project (from 'Start Date')"),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('delayed', 'Delayed')], default='planned', help_text="Current project status (from 'Status')", max_length=20),
        ),
    ]
