"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Base directory
BASE_DIR = Path(__file__).resolve().parent.parent

# Security
SECRET_KEY = os.getenv("SECRET_KEY", "insecure-secret-key")
DEBUG = os.getenv("DEBUG", "False").lower() in ["true", "1", "yes"]

# Toggle between SQLite+SpatiaLite (local) and PostGIS (production)
DB_LIVE = os.getenv("DB_LIVE", "False").lower() in ["true", "1", "yes"]

# Allowed hosts
ALLOWED_HOSTS = [
    "kitui-project.onrender.com",
    "www.kitui-project.onrender.com",
    "localhost",
    "127.0.0.1",
]

# CSRF trusted origins
CSRF_TRUSTED_ORIGINS = [
    "https://kitui-project.onrender.com",
    "https://www.kitui-project.onrender.com",
]

# -------------------------------------------------------
# Application definition
# -------------------------------------------------------
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "django.contrib.gis",   # GIS support
    "leaflet",
    "channels",             # 👇 ADDED: for WebSocket support
    "app",                  # your main app
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# 👇 ADDED: ASGI application (replaces plain WSGI)
ASGI_APPLICATION = "project.asgi.application"

# Keep WSGI for compatibility (some hosts use it)
WSGI_APPLICATION = "project.wsgi.application"

# -------------------------------------------------------
# Database configuration
# -------------------------------------------------------
if DB_LIVE:
    DATABASES = {
        "default": {
            "ENGINE": "django.contrib.gis.db.backends.postgis",
            "NAME": os.getenv("DB_NAME"),
            "USER": os.getenv("DB_USER"),
            "PASSWORD": os.getenv("DB_PASSWORD"),
            "HOST": os.getenv("DB_HOST"),
            "PORT": os.getenv("DB_PORT", "5432"),
            "OPTIONS": {
                "sslmode": "require",   # 👈 Forces SSL for Render
            },
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.contrib.gis.db.backends.spatialite",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
    SPATIALITE_LIBRARY_PATH = "/usr/lib/x86_64-linux-gnu/mod_spatialite.so"


# -------------------------------------------------------
# 👇 ADDED: Channels configuration (WebSocket backend)
# -------------------------------------------------------
# You’ll need Redis running locally or via Docker
# For production, use a managed Redis (Render or Upstash)
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(
                os.getenv("REDIS_HOST", "127.0.0.1"),
                int(os.getenv("REDIS_PORT", 6379))
            )],
        },
    },
}

# -------------------------------------------------------
# Password validation
# -------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# -------------------------------------------------------
# Internationalization
# -------------------------------------------------------
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# -------------------------------------------------------
# Static & Media files
# -------------------------------------------------------
STATIC_URL = "/static/"
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# -------------------------------------------------------
# Leaflet config
# -------------------------------------------------------
LEAFLET_CONFIG = {
    "DEFAULT_CENTER": (-1.286, 36.817),  # Nairobi
    "DEFAULT_ZOOM": 7,
    "MIN_ZOOM": 3,
    "MAX_ZOOM": 18,
    "RESET_VIEW": False,
    "SCALE": "metric",
    "ATTRIBUTION_PREFIX": "Geospatial Project Monitoring System - Kenya",
}

# -------------------------------------------------------
# Default primary key
# -------------------------------------------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

